### ISSUE TITLE
[proposal] add interface for client type

### ISSUE THREAD

**Issue by costela** [hetznercloud/hcloud-go#100]
Using interfaces instead of structs for the client would make writing tests with mocks considerably easier.

Right now, in order to write "grey-box" tests mocking API calls, I can't see any other way than wrapping the client in an interface myself, but this means some non-testable boiler-plate code that could introduce or hide subtle bugs.

The current nested-`struct` API would of course have to remain for backward-compatibility, but I believe adding an interface layer above it should be relatively straightforward. Something like:
```go
type Clienter interface {
  Volume() Volume
  ...
}
```
With the accompanying implementations for each "getter" methods.

Or maybe even going full-on interface (though the gains in this case seem less significant):
```go
type Clienter interface {
  Volume() VolumeClienter
  ...
}
type VolumeClienter interface {
  All(ctx context.Context) ([]*Volume, error)
  ...
}
```

This feels like a rather minor change. Am I maybe overlooking something?
Otherwise: thoughts?

**Comment by thcyron** [comment]
Problem with that approach is that we would not be able to add new methods to a client without introducing a breaking change.

Version 1.0:

```go
type ServerClient interface {
    GetByID(context.Context, id int) (*Server, error)
}
```

Version 1.1:

```go
type ServerClient interface {
    GetByID(context.Context, id int) (*Server, error)
    Delete(context.Context, *Server) error
}
```

Version 1.1 would need to be version 2.0 because it will break all 1.0 users.

**Comment by thcyron** [comment]
@costela FYI: https://github.com/golang/go/wiki/CodeReviewComments#interfaces
