### ISSUE TITLE
Pass more parameters for images

### ISSUE THREAD

**Issue by LukBukkit** [hetznercloud/hcloud-go#106]
Hello,

it would be nice if I could pass parameters like `type` to the [`images` endpoint](https://docs.hetzner.cloud/#images-get-all-images).
I guess to accomplish this, the [ImageListOpts](https://github.com/hetznercloud/hcloud-go/blob/master/hcloud/image.go#L122) must be extended.

**Comment by LukBukkit** [comment]
One more question: Does the `name` for the [/images](https://docs.hetzner.cloud/#images-get-all-images) endpoint parameter only work with names of `system` images?

**Comment by thcyron** [comment]
> One more question: Does the `name` for the [/images](https://docs.hetzner.cloud/#images-get-all-images) endpoint parameter only work with names of `system` images?

Yes, because only image of type system have a name. Images of other types only have a description.
