### ISSUE TITLE
refresh time of traffic values

### ISSUE THREAD

**Issue by shibumi** [hetznercloud/hcloud-go#117]
I can't find any documentation about it, so I try my luck here.
How often are the following values refreshed for the server API:

```
  "included_traffic": 21990232555520,
  "ingoing_traffic": 4161740000,
....
  "outgoing_traffic": 20802648000,
```

These values seem pretty static to me (I did several things that should have an effect on the server traffic, e.g. downloading big files etc). Is there a command line option for hcloud to increase the refresh time or is there at least something like a SLA that defines 'freshness' of the API data?

**Comment by thcyron** [comment]
These values are updated once per hour. However, the numbers aren’t accurate to the byte due to how traffic accounting works.

**Comment by shibumi** [comment]
Hi @thcyron thanks for the reply. Do you know if there are any plans to decrease this refresh value? 1h is pretty slow for an API and could you please document this somewhere in the API documentation?

**Comment by thcyron** [comment]
No, there are no plans to update traffic data more often.

@LKaemmerling Please evaluate if it makes sense to include the update interval in our docs.
