### ISSUE TITLE
Provide api mock for testing

### ISSUE THREAD

**Issue by FedeBev** [hetznercloud/hcloud-go#124]
It would be nice to have a mock suite in order to be easily able to perform e2e test.
In my opinion it would be enough to extract the mocks already present in the tests.

For example: considering the [GetByID action test](https://github.com/hetznercloud/hcloud-go/blob/master/hcloud/action_test.go#L13), it defines the mock as shown belown
```go
env.Mux.HandleFunc("/actions/1", func(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(schema.ActionGetResponse{
		Action: schema.Action{
			ID:       1,
			Status:   "running",
			Command:  "create_server",
			Progress: 50,
			Started:  time.Date(2017, 12, 4, 14, 31, 1, 0, time.UTC),
		},
	})
})
```
that could be done in a separate package

**Comment by LKaemmerling** [comment]
We already have a custom contributed mock: https://github.com/LKDevelopment/hetzner-cloud-api-mock

We use this mock in our python lib and are quite happy with this.

**Comment by FedeBev** [comment]
I think this is not the best situation, the library for some tests uses internal derision and external for others. Am I wrong?

Anyway, thanks for the advice!

**Comment by LKaemmerling** [comment]
Yep we already now this and have this on our list. We want to change it in the hcloud-go too.

**Comment by JefMasereel** [comment]
Any updates on this mock suite for hcloud-go? The hetzner-cloud-api-mock referred to earlier is no longer maintained, and it would be good to have an up-to-date mocking tool available. Please let me know if I missed any recent developments.

**Comment by jangraefen** [comment]
Hello @LKaemmerling,

I am currently writing a test suite for the [hcloud-pricing-exporter](https://github.com/jangraefen/hcloud-pricing-exporter), because of the issues discovered [here](https://github.com/jangraefen/hcloud-pricing-exporter/pull/40) in conjunction with #222.

The original repository is no longer maintained and is archived. It would be really nice to have a possibility to write tests without spending real money. After all, this is open source we are doing in our free time. Hetzner is also profiting from a flourishing open source ecosystem, with high quality projects 🙂.

I am open about the actual solution to this problem, but having something would be really awesome ❤️

**Comment by apricote** [comment]
Hi @jangraefen, we do not currently provide a standalone mocking tool. Some possible solutions for you:

### Mocking hcloud-go clients

For [`cli`](https://github.com/hetznercloud/cli) we use `go generate` with [`interfacer`](https://github.com/rjeczalik/interfaces/#cmdinterfacer-) and [`mockgen`](https://github.com/golang/mock#running-mockgen) to mock out the hcloud-go implementation for our tests. This does not test against the "real" api, but any mock implementation would suffer from the same staleness problems, as they also need to be kept up-to-date manually (unless it uses a public OpenAPI spec).

- Interface Gen: https://github.com/hetznercloud/cli/blob/main/internal/hcapi2/interface_gen.go
- Mock Gen: https://github.com/hetznercloud/cli/blob/main/internal/hcapi2/mock/mock_gen.go
- Example Interface for Primary IPs: https://github.com/hetznercloud/cli/blob/main/internal/hcapi2/zz_primary_ip_client_base.go
- Example Mock for Primary IPs: https://github.com/hetznercloud/cli/blob/main/internal/hcapi2/mock/zz_primary_ip_client_mock.go
- Usage in Test: https://github.com/hetznercloud/cli/blob/ec1ecfd1972a16899add2212609cb6ad6201f8ec/internal/cmd/primaryip/create_test.go#L13-L43

### Using OpenAPI spec to generate Mock

You can use an OpenAPI specification for the Hetzner Cloud API to automatically generate mocks. We publish the OpenAPI spec at https://docs.hetzner.cloud/spec.json but we do not provide any guarantees for this, so the format, content or path may change at any moment. There is also an unofficial OpenAPI spec published: [MaximilianKoestler/hcloud-openapi](https://github.com/MaximilianKoestler/hcloud-openapi)

For generating the mock, there are tools such as [muonsoft/openapi-mock](https://github.com/muonsoft/openapi-mock), but I have not personally tested this.

**Comment by jangraefen** [comment]
Hey @apricote,

thank you for your quick response!
These resources look quit promising to write unit or module tests and I will definitly consider using some of this to test some specific areas of my project. Thank you for these links 🙂.

For proper integration or end-to-end testing, these methods fall abit short though, as you also pointed out. The mock will just be as flawed as the implementation, if the assumption made about the workings of the API are wrong. My proposal would be to provide a more suffisticated solution. Examples could be:
- Provide a staging area or provide a flag for HCloud Projects to be marked as "staging projects". API calls do not create real resources, but just create the data set. If I create a server, I can later query it when using `GET /servers` or `GET/servers/{id}`, but it is not actually created or running. Maybe I could still attach e.g. a floating IP to it, with the IP being none existend as well of course.
- Even more suffisticated: Provide a dockerized version of the API in a similar fashion as the staging area proposal. Think AWS localstack, but without actually creating stuff.
- Pragmatic solution: Just give a small allowance to open source projects for testing. Something along the lines of 3-5€ max should be sufficient. I am aware of the 50€ one time offer, which is already very generous, but gets drained eventually, especially if tests a run on every commit the main branch or incoming PRs.

I get that this is a pretty big ask and alot of effort goes into providing these kind of mocks. However I believe that in the long run, providing reliable and cost-effective means for testing to open source projects really brings alot in terms of quality to the HCloud ecosystem, which directly benefits Hetzner 😉.

To make a long story short: I know this won't be resolved in the short term and I will need to invest some of my own money, to ensure a certain quality standard in a project I am providing for free to the wider community. But it is a bit disheartening to see this issue closed, with no possibility on the horizon for an alternative.
