### ISSUE TITLE
PublicNet IPv4/IPv6 is nil after creating a loadbalancer

### ISSUE THREAD

**Issue by yhc44** [hetznercloud/hcloud-go#153]
Hello, when i am creating a loadbalancer the responses PublicNet ipv4 and ipv6 value is null.

I put a debug statement into client.go to see where the error comes from.

It seems that the api does not return the right public net of the loadbalancer.

```json
"load_balancer": {
    "id": 12345,
    "name": "xxx",
    "public_net": {
      "enabled": true,
      "ipv4": {
        "ip": null <--
      },
      "ipv6": {
        "ip": null <--
      }
    },
```

**Comment by yhc44** [comment]
My temporary fix is to get the created loadbalancer immediately after i created it. The returned object holds the valid ip addresses.

**Comment by thcyron** [comment]
That’s correct behavior. `ipv4` and `ipv6` are only present after the `create_load_balancer` action returned in [Create a Load Balancer](https://docs.hetzner.cloud/#load-balancers-create-a-load-balancer) has completed, i.e. its status is `success`.
