### ISSUE TITLE
Type []*SSHKey

### ISSUE THREAD

**Issue by hookzof** [hetznercloud/hcloud-go#156]
Hi, I try to add a key via `&hcloud.SSHKey{}`, but I encounter this error:

`Cannot use '&hcloud.SSHKey{}' (type *SSHKey) as type []*SSHKey`

How can I wrap it to make it work? Thank you.

**Comment by hookzof** [comment]
This seems to work for me:

`[]*hcloud.SSHKey{{Name: "API"}}`

**Comment by LKaemmerling** [comment]
> This seems to work for me:
> 
> `[]*hcloud.SSHKey{{Name: "API"}}`

Yep, this is the correct notation because you can add multiple ssh keys to the server.
