### ISSUE TITLE
Allow booting ipxe images

### ISSUE THREAD

**Issue by flokli** [hetznercloud/hcloud-go#160]
This is more of a feature request to the platform itself:

I'd be super convenient if it'd be possible to boot hcloud servers via IPXE, by selecting "ipxe" as a "os type", and pointing to a custom URL.

It could be made possible by a custom ipxe image that [fetches a special field from the metadata servers http endpoint](https://ipxe.org/embed).

That'd simplify booting new images like Fedora Core OS, Flatcar or custom images dramatically.

The `user-data` field should probably not be used for this, because these OSes use it to read their cloud-init configuration from.

**Comment by LKaemmerling** [comment]
Hey @flokli, 

I passed the request to our Product Team. As this is not directly related to the hcloud-go I would like to close the issue.  If you have other feature ideas, feel free to write a support ticket :)

Thank you!
