### ISSUE TITLE
Spawning a new instance inside a private network does not return private IP.

### ISSUE THREAD

**Issue by tomjohnburton** [hetznercloud/hcloud-go#168]
I am spawning a server inside a private network as shown below. Yet, as can be seen in the logs, the response does not return the IP of that newly created server. It just says `null`.

Any help would be greatly appreciated :D
![image](https://user-images.githubusercontent.com/39559415/117701775-eb58b680-b1c7-11eb-82ed-79903d8b6fa4.png)

```
,"Rules":null,"AppliedTo":null},"Status":"applied"}]},"PrivateNet":null,"ServerType":{"ID":23,"Name":"cpx21"
```

**Comment by LKaemmerling** [comment]
Hey @tomjohnburton,

the IP is only available when the network_attach action is successful, so you need to refetch the server.

**Comment by tomjohnburton** [comment]
Thanks @LKaemmerling , is there a way to set up a hook when that action is successful?

**Comment by LKaemmerling** [comment]
@tomjohnburton you can watch the action progress (Action Client: `WatchOverallProgress `). The methods blocks until the action is success (you need to consume the channels). after this you can easily query the server again.
Sample: https://github.com/hetznercloud/cli/blob/master/internal/cmd/server/attach_to_network.go#L70
https://github.com/hetznercloud/cli/blob/3d72d344d9b572725fcb9e39726f9bbdafdb2bcc/internal/state/helpers.go#L188
