### ISSUE TITLE
Provide user_data back when getting a server

### ISSUE THREAD

**Issue by hakman** [hetznercloud/hcloud-go#200]
User-data is an important part of automating deployments especially when it comes to Kubernetes.

The Hetzner Cloud API allows setting the user-data when creating a server, but you cannot read it back later when getting/describing the server. This makes it harder to compare servers with a template and recycle them.

I would like to have user-data, or at least a hash of it available when getting/describing a server.

**Comment by LKaemmerling** [comment]
Hey @hakman,

I'm sorry but this is not possible. At the moment we don't store the userdata, so basically it is just passed on to the instance on the creation and then from our side, it is "gone", so there is no way to return the userdata after server creation. One thing you could do would be adding a label based on a hash of the userdata to all of your servers.

**Comment by hakman** [comment]
@LKaemmerling  I can add the userdata hash as a label (actually already doing this).
I was thinking more of what happens when using cluster-autoscaler later and that one is quite clueless about this and I would  really like to use cluster-autoscaler.
