### ISSUE TITLE
Hetzner Project Management API endpoints

### ISSUE THREAD

**Issue by edelesel** [hetznercloud/hcloud-go#208]
For some project I would need to:
* Create subprojects (billed via my hetzner account) via API
* delete those projects (all resources created in the project should get deleted too)
* Add cost limits to those projects via API
* Create tokens for those projects via API
* Get the current costs for the projects via API

I haven't found a hint that this is supported here: https://docs.hetzner.cloud/#overview

Do you have plans to implement such APIs?

**Comment by apricote** [comment]
Hey @edelesel,

thank you for the detailed suggestion. I have added 5 votes to our internal feature request tracker for adding a project API.

Right now, our public API only supports things happening inside of one project.
