### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [hetznercloud/hcloud-go#226]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in an Hetzner Cloud plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Hetzner Cloud data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by apricote** [comment]
Hi @yevgenypats,

CloudQuery.io sounds very interesting, but unfortunately we do not have the bandwidth to support/maintain additional integrations at the moment.

If you do go ahead and develop the integration, you qualify for a € 50 credit to your cloud account. See ["Do you sponsor efforts to integrate Hetzner Cloud into Open Source libs?"](https://docs.hetzner.com/cloud/api/faq/#do-you-sponsor-efforts-to-integrate-hetzner-cloud-into-open-source-libs) in our API FAQ.
