### ISSUE TITLE
No password when rebuilding from image

### ISSUE THREAD

**Issue by slade991** [hetznercloud/hcloud-go#244]
Hello,

The hetzner API return the new root password when rebuilding :
Response

    actionobject
    root_passwordstring – nullable

    New root password when not using SSH keys

But hcloud doesn't

Why is that ? Is it possible to get the new root password ?

Thank you.

**Comment by apricote** [comment]
I added a new method `ServerClient.RebuildWithResult()` that returns the root password in addition to the action. This was released as `v1.41.0`.

**Comment by slade991** [comment]
Wow. That was fast.
Thanks a ton.
