### ISSUE TITLE
Hetzner API request: ability to know if server count limit has been reached

### ISSUE THREAD

**Issue by aral** [hetznercloud/hcloud-go#302]
It would be useful to have an endpoint with information about the current state of your account regarding resource/server limits so errors can be prevented.

## Use case

I just hit a `resource_limit_exceeded` error because I already had 10 VPS servers in my account.

If I could have checked something like `account.server_limit` and `account.server_count`, I could have had the interface display a message “Your Hetzner account has reached its limit of N servers and you cannot currently create any new ones. Please contact Hetzner to upgrade your limit.” and not have allowed the attempt to be made.

(It’s always better to prevent an error condition when you can do so reliably instead of having the person hit the error and then be disappointed.)

**Comment by apricote** [comment]
Hey @aral,

I have added a vote to our internal feature request tracker for adding Limit information to our public API.

**Comment by aral** [comment]
@apricote Thanks, Julian, appreciate it :)
