### ISSUE TITLE
Using pointers for basic types

### ISSUE THREAD

**Issue by sbusso** [hetznercloud/hcloud-go#344]
Hello there! I am currently trying to utilize the `hcloud-go` library for server management. The first function I need to use is `client.Server.Create`, which requires a pointer boolean as one of its parameters. From my research, I believe the correct way to pass a pointer boolean is by using the `Ptr` function, like so: `hcloud.Ptr(true)`. However, I'm not quite familiar with creating pointers for basic types. Could you please help me understand why pointers are used in this context? Thank you!

**Comment by jooola** [comment]
Hi @sbusso 

> Could you please help me understand why pointers are used in this context?

Pointers can be used to denote the absence of a value, for example `bool` default to false when not set, but `*bool` can be null, false and true.

Maybe there are other reasons why pointers were used.

I hope this answers your question?

**Comment by sbusso** [comment]
Thanks, @jooola, but that doesn't answer the question. For example, in the case of server creation, the boolean field is `StartAfterCreate`; how would null differ from the default?

**Comment by jooola** [comment]
According to https://docs.hetzner.cloud/#servers-create-a-server the default for `start_after_create` is true. When creating a [ServerCreateOpts](https://pkg.go.dev/github.com/hetznercloud/hcloud-go/v2/hcloud#ServerCreateOpts) struct, if we use a `bool` type, the "client side" default would be `false`, by using a pointer `*bool`, the "client-side" default will be null, and we leave the "server-side" default step in.

**Comment by sbusso** [comment]
I see. thanks @jooola
