### ISSUE TITLE
Search matches only whole words

### ISSUE THREAD

**Issue by alexandernst** [hetznercloud/hcloud-go#358]
Let's say I have the following servers:

```
* aaa
* bbb
* ccc
```

If I `GET` the `/servers` API endpoint and I use the `name=a` or `name=a*` filter, I won't get any results. If I use `name=aaa`, I'll get the `aaa` server.

The `name` filter is matching against whole words. Is that a feature or a bug?

**Comment by jooola** [comment]
This is not a bug, the API has been implemented this way for all endpoints. At this point, I cannot tell you if the feature you are describing will be implemented.

Related to https://github.com/hetznercloud/hcloud-python/issues/334
