### ISSUE TITLE
API of add/remove target to/from load balancer is inconsistent with console UI

### ISSUE THREAD

**Issue by alexandernst** [hetznercloud/hcloud-go#406]
### TL;DR

In the console I can add/remove multiple servers (targets) to/from a load balancer at once, but with the API's [add](https://docs.hetzner.cloud/#load-balancer-actions-add-target) and [remove](https://docs.hetzner.cloud/#load-balancer-actions-remove-target) target I'm allowed to add/remove a single server at a time.

I'm aware that this is not specific to the Go library, but rather a general API ¿problem?, but I'm not sure where else should I fill this report.

### Expected behavior

I should be able to add/remove multiple targets at the same time using the API.

**Comment by jooola** [comment]
To do batch updates, we leverage an internal endpoint not meant for the public, which is therefor not implemented in this library.

I forwarded your request to our internal feedback tracker.
