### ISSUE TITLE
Add `load_balancers` field in network response schema

### ISSUE THREAD

**Issue by 0x221A** [hetznercloud/hcloud-go#567]
### TL;DR

Currently, there is no `load_balancers` field in the network response schema which the API has returned but it's not decoded into the struct.

### Expected behavior

Add `load_balancers` field in the network response schema.

https://github.com/hetznercloud/hcloud-go/blob/9056ee6f38315466268e71e67c049f9fbc39ea72/hcloud/schema/network.go#L6-L17

**Comment by jooola** [comment]
Thanks for the hint, should be fixed in the next release :)
