### ISSUE TITLE
Call close on response body method to prevent a resource leak

### ISSUE THREAD

**Issue by mmichaelb** [hetznercloud/hcloud-go#68]
Not closing the body of HTTP responses can lead to a huge resource leak when doing HTTP requests intensively. The connection probably can remain open, in which case the file descriptor won't be freed. After some time this can cause you to get a 'too many files open' error. Therefore inserting a close statement right before wrapping the response body would be a good change. 

I would be willing to make this change because I have already forked the project, but would like to have the ok from the project owners. If I have misunderstood something or the response is already closed, please let me know.

**Comment by thcyron** [comment]
Thank you! Fixed with #69.
