### ISSUE TITLE
Allow SSHKey fingerprint instead of SSHKey ID

### ISSUE THREAD

**Issue by tboerger** [hetznercloud/hcloud-go#77]
While creating an instance it could be nice to use the SSHKey fingerprint instead of the primary key of an SSHKey. Looks like that API already supports that as an undocumented feature.

I would like to use that for a Hetzner Cloud integration to avoid another roundtrip to get the ID for a key instead of simply providing the fingerprint.

**Comment by thcyron** [comment]
Won’t be implemented. See #78 for reasoning behind that decision.
