### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by ariselseng** [hetznercloud/hcloud-go#94]
It would be nice if I could get some metrics like in the API.

**Comment by yhc44** [comment]
Anything new on this? Would like to use metrics in my go project using the hcloud-go API.

I currently use my own Library for this

**Comment by LKaemmerling** [comment]
@yhc44 we are discussing internally if this really fits within the hcloud-go. What is your specific use case to need the data?

**Comment by hookzof** [comment]
@LKaemmerling in my case it's autoscaling on traffic data + CPU.

**Comment by yhc44** [comment]
For me its the same like @hookzof said.

I need metrics to auto rescale servers that are in my managed kubernetes cluster.

**Comment by LKaemmerling** [comment]
@yhc44 do you want to contribute your change to the hcloud-go upstream (if you are using this within your own library)? Otherwise, I would like to implement this within the next few weeks (for servers and load balancers).

**Comment by yhc44** [comment]
@LKaemmerling i work on other projects at the moment and didnt finish the own implementation, so its not complete, sorry.
