### ISSUE TITLE
Querying non-existent objects does not return an error

### ISSUE THREAD

**Issue by mhutter** [hetznercloud/hcloud-go#99]
**Steps to reproduce**

```go
c := hcloud.NewClient(hcloud.WithToken(token))
_, err := c.Server.GetByID(context.Background(), nonExistentID)
fmt.Println(err)
```

**Actual result**

    nil

**Expected result**

    Server with ID #1234 not found

In my case, querying a non-existent resource clearly is an error condition. Right now to handle both cases, ugly hacks have to be implemented:

```go
srv, err := c.Server.GetByID(context.Background(), nonExistentID)
if err != nil {
    // errors.Wrap() returns nil if err is nil
    return errors.Wrap(err, "error querying server")
}
if srv == nil {
    return errors.New("server not found")
}
```

**Comment by thcyron** [comment]
Well, these are the two ways how to denote a “not found” error in a query function. We went for `nil` and are not going to change that API — at least not for v1.

**Comment by mhutter** [comment]
Fine by me, but this should at least be mentioned in the godocs since it deviates from what people would expect from idiomatic go.

**Comment by thcyron** [comment]
True. Did just that: a68fcd00bd9798a8b2733490911fbef5ab7d9885

**Comment by mhutter** [comment]
Cool, thanks!
